apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      web: resto
  template:
    metadata:
      labels:
        web: resto
    spec:
      containers:
        - name: resto-web
          image: manchi189/web-img:latest
          ports:
            - containerPort: 80
  