apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      web: resto
  template:
    metadata:
      labels:
        web: resto
    spec:
      containers:
        - name: resto-web
          image: nginx:latest
          ports:
            - containerPort: 80
  