apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-port-deployment
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-port-container
          image: manchi189/ecommerce-web:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-svc
spec:
  selector:
    app: node
  ports:
    - port: 82
      targetPort: 80
      potocol:TCP
  type: NodePort