apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-autoscale
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: mycont
          image: nginx:latest
          ports:
            - contanerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi