apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  containers:
    - name: netflix-cont
      image: manchi189/netflix:latest
      ports:
        - containerPort: 80

    
  