apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      web: app
  template:
    metadata:
      labels:
        web: app
    spec:
      containers:
        - name: netflix-cont
          image: manchi189/netflix:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
spec:
  selector:
    web: app
  ports:
    - port: 81
      targetPort: 80
      protocol: TCP
  type: LoadBalancer

    
  